name: Create PR to PreRelease

on:
  push:
    branches:
      - master  # ここはpush元のブランチ名に応じて調整してください2

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # 使用しているGoのバージョンに合わせてください

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          # branch: ${{ github.ref_name }}
          title: 'Auto PR from ${{ github.ref_name }} to main'
          body: |
            This PR was automatically created by GitHub Actions.
            Source branch: ${{ github.ref_name }}
