name: Test

on:
  workflow_run:
    workflows: ['Static analysis']      # 上の name と一致させる
    types: [completed]           # 完了時のみトリガー

# on:
#   pull_request:                     #プルリクエストが作成されたら起動
#     paths: ['go/**/*.go']           #ただしGoのファイル変更時のみ

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   #ステップ１：チェックアウト
      - uses: actions/setup-go@v5   #ステップ２：言語セットアップ
        with:
          go-version: '1.22'
      - run: go test go/excellent/*.go #ステップ３：テストの実行
